language: generic 
sudo: required
services:
  - docker

before_install:
  - docker build -t aliwatters/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true aliwatters/react-test npm test

after_success:
  - docker build -t aliwatters/dkcc-client ./client
  - docker build -t aliwatters/dkcc-server ./server
  - docker build -t aliwatters/dkcc-nginx ./nginx
  - docker build -t aliwatters/dkcc-worker ./worker
  # login to docker CLI
  - docker login -u "$DOCKER_ID" -p "$DOCKER_PASSWORD"
  # push images to dockerhub (or aws/do etc)
  - docker push aliwatters/dkcc-client 
  - docker push aliwatters/dkcc-nginx 
  - docker push aliwatters/dkcc-server 
  - docker push aliwatters/dkcc-worker

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "dkcc"
  env: "Dkcc-env"
  bucket_name: "elasticbeanstalk-us-east-2-621861701423"
  bucket_path: "dkcc"
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY